job_name          : 'J1_HandPose_MuscleFixed'

env               :   HandPose0MuscleFixed-v0
algorithm         :   NPG
seed              :   123
sample_mode       :   trajectories
rl_num_samples    :   0
rl_num_traj       :   100
rl_num_iter       :   1001
num_cpu           :   16
save_freq         :   100
eval_rollouts     :   10
exp_notes         :  'first iteration'

policy_size       :   (32, 32)
init_log_std      :   -0.25
min_log_std       :   -1.0
vf_hidden_size    :   (128, 128)
vf_batch_size     :   64
vf_epochs         :   2
vf_learn_rate     :   1e-3
rl_step_size      :   0.1
rl_gamma          :   0.995
rl_gae            :   0.97


alg_hyper_params  :   {'device': 'cpu'}

hydra:
    job:
        name: ${oc.env}


