default:
- override hydra/output: local
- override hydra/launcher: local
env: kitchen_knob4_on-v3
algorithm: NPG
seed: 2
sample_mode: trajectories
rl_num_traj: 200
rl_num_samples: 0
num_cpu: 10
rl_num_iter: 501
save_freq: 100
eval_rollouts: 10
exp_notes: V0.3 Baseline
policy_size: (64, 64)
init_log_std: -0.1
min_log_std: -1.0
vf_hidden_size: (128, 128)
vf_batch_size: 64
vf_epochs: 2
vf_learn_rate: 0.001
rl_step_size: 0.05
rl_gamma: 0.995
rl_gae: 0.97
alg_hyper_params:
  device: cpu
job_name: job
